# Triggers: Manual on chosen environment

name: "[PR] Format, Validate and Plan"
concurrency: ${{ github.workflow }}
on:
  pull_request:
    branches:    
      - main
    paths:
      - '**.tf'

env:
  ARM_USE_AZUREAD: "true"
  AZURE_ENVIRONMENT: "dev"

jobs:
  variables:
    name: Variables
    runs-on: ubuntu-latest
    outputs:
      GITHUB_SHA_SHORT: ${{ steps.variables.outputs.GITHUB_SHA_SHORT }}
      GITHUB_BRANCH_SLUG: ${{ steps.variables.outputs.GITHUB_BRANCH_SLUG }}
      GITHUB_REPO_NAME: ${{ steps.variables.outputs.GITHUB_REPO_NAME }}
    steps:
      - uses: actions/github-script@v6
        id: variables
        with:
          script: |
            const sha = context.sha.substring(0,7)
            const branch = context.ref.split('/').pop()
            const repo_name = context.payload.repository.full_name.split('/').pop().toLowerCase()
            core.setOutput('GITHUB_SHA_SHORT', sha)
            core.setOutput('GITHUB_BRANCH_SLUG', branch)
            core.setOutput('GITHUB_REPO_NAME', repo_name)
  terraform:
    name: "Terraform Validate and Plan"
    needs: [ variables ]
    runs-on: ubuntu-latest
    concurrency: terraform-${{ env.AZURE_ENVIRONMENT }}
    environment: 
      name: ${{ env.AZURE_ENVIRONMENT }}-plan
    
    env:
      # Target subscription
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}  # always same!

      # Backend terraform state
      TF_BACKEND_RG_NAME: ${{ secrets.DEMO_PREFIX }}-rg-${{ env.AZURE_ENVIRONMENT }}-tfstate
      TF_BACKEND_STGACCT_NAME: ${{ secrets.DEMO_PREFIX }}${{ env.AZURE_ENVIRONMENT }}tfstate
      TF_BACKEND_CONTAINER_NAME: tfstate
      TF_BACKEND_KEY: ${{ needs.variables.outputs.GITHUB_REPO_NAME }}/${{ env.AZURE_ENVIRONMENT }}.tfstate

      # Env vars accessible inside Terraform files
      TF_VAR_azure_environment: ${{ env.AZURE_ENVIRONMENT }}
      TF_VAR_subscription_id: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      TF_VAR_github_sha: ${{ needs.variables.outputs.GITHUB_SHA_SHORT }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -no-color -diff

      - name: Terraform Init
        id: init
        run: |
          terraform init -input=false -upgrade \
            -backend-config="resource_group_name=${TF_BACKEND_RG_NAME}" \
            -backend-config="storage_account_name=${TF_BACKEND_STGACCT_NAME}" \
            -backend-config="container_name=${TF_BACKEND_CONTAINER_NAME}" \
            -backend-config="key=${TF_BACKEND_KEY}" 
        
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false